
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Frame parametersFrame;
	
	private global::Gtk.Alignment GtkAlignment;
	
	private global::Gtk.Table table2;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.ComboBoxEntry logFilePath;
	
	private global::Gtk.Button button4;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Label parametersFrameLabel;
	
	private global::Gtk.Table table3;
	
	private global::Gtk.Button buttonGenerate;
	
	private global::Gtk.Fixed fixed5;
	
	private global::Gtk.Fixed fixed6;
	
	private global::Gtk.Frame outputFrame;
	
	private global::Gtk.Alignment GtkAlignment1;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView textview1;
	
	private global::Gtk.Label outputFrameLabel;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(10));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.parametersFrame = new global::Gtk.Frame ();
		this.parametersFrame.Name = "parametersFrame";
		this.parametersFrame.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child parametersFrame.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(10));
		this.GtkAlignment.TopPadding = ((uint)(10));
		this.GtkAlignment.RightPadding = ((uint)(10));
		this.GtkAlignment.BottomPadding = ((uint)(10));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.table2 = new global::Gtk.Table (((uint)(2)), ((uint)(1)), true);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.logFilePath = global::Gtk.ComboBoxEntry.NewText ();
		this.logFilePath.AppendText (global::Mono.Unix.Catalog.GetString ("/home/user/logs/ping_log"));
		this.logFilePath.Name = "logFilePath";
		this.hbox2.Add (this.logFilePath);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.logFilePath]));
		w1.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString ("...");
		this.hbox2.Add (this.button4);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button4]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.table2.Add (this.hbox2);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.hbox2]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.YOptions = ((global::Gtk.AttachOptions)(0));
		// Container child table2.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.Xalign = 0F;
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Имя анализируемого файла:");
		this.label3.Justify = ((global::Gtk.Justification)(3));
		this.table2.Add (this.label3);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.label3]));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment.Add (this.table2);
		this.parametersFrame.Add (this.GtkAlignment);
		this.parametersFrameLabel = new global::Gtk.Label ();
		this.parametersFrameLabel.Name = "parametersFrameLabel";
		this.parametersFrameLabel.Yalign = 0F;
		this.parametersFrameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Параметры</b>");
		this.parametersFrameLabel.UseMarkup = true;
		this.parametersFrame.LabelWidget = this.parametersFrameLabel;
		this.vbox2.Add (this.parametersFrame);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.parametersFrame]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.table3 = new global::Gtk.Table (((uint)(1)), ((uint)(3)), true);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(6));
		this.table3.ColumnSpacing = ((uint)(6));
		// Container child table3.Gtk.Table+TableChild
		this.buttonGenerate = new global::Gtk.Button ();
		this.buttonGenerate.CanFocus = true;
		this.buttonGenerate.Name = "buttonGenerate";
		this.buttonGenerate.UseUnderline = true;
		this.buttonGenerate.Label = global::Mono.Unix.Catalog.GetString ("Обработать!");
		this.table3.Add (this.buttonGenerate);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonGenerate]));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.fixed5 = new global::Gtk.Fixed ();
		this.fixed5.Name = "fixed5";
		this.fixed5.HasWindow = false;
		this.table3.Add (this.fixed5);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed5]));
		w9.LeftAttach = ((uint)(2));
		w9.RightAttach = ((uint)(3));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.fixed6 = new global::Gtk.Fixed ();
		this.fixed6.Name = "fixed6";
		this.fixed6.HasWindow = false;
		this.table3.Add (this.fixed6);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table3 [this.fixed6]));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox2.Add (this.table3);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table3]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.outputFrame = new global::Gtk.Frame ();
		this.outputFrame.Name = "outputFrame";
		this.outputFrame.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child outputFrame.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView ();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.GtkScrolledWindow.Add (this.textview1);
		this.GtkAlignment1.Add (this.GtkScrolledWindow);
		this.outputFrame.Add (this.GtkAlignment1);
		this.outputFrameLabel = new global::Gtk.Label ();
		this.outputFrameLabel.Name = "outputFrameLabel";
		this.outputFrameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Журнал выполненных операций</b>");
		this.outputFrameLabel.UseMarkup = true;
		this.outputFrame.LabelWidget = this.outputFrameLabel;
		this.vbox2.Add (this.outputFrame);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.outputFrame]));
		w15.Position = 2;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 671;
		this.DefaultHeight = 653;
		this.label3.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.buttonGenerate.Clicked += new global::System.EventHandler (this.generateButtonHander);
	}
}
